// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2cNTdovGJEfOADOlBrz3kNyHg0n1a0Vw',
    appId: '1:453591806698:web:d951c274e479433843dd93',
    messagingSenderId: '453591806698',
    projectId: 'neurocare-connect-44235',
    authDomain: 'neurocare-connect-44235.firebaseapp.com',
    storageBucket: 'neurocare-connect-44235.firebasestorage.app',
    measurementId: 'G-VXNK8QBC4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5LepnbmgZ5Jk7oCnF_6wOAuIXCgkJEYE',
    appId: '1:453591806698:android:5253eab3ba7cd97343dd93',
    messagingSenderId: '453591806698',
    projectId: 'neurocare-connect-44235',
    storageBucket: 'neurocare-connect-44235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3_wgvyEHYVb86zRrOfUn50dtG4YgKRbo',
    appId: '1:453591806698:ios:23399a9a34d17f4743dd93',
    messagingSenderId: '453591806698',
    projectId: 'neurocare-connect-44235',
    storageBucket: 'neurocare-connect-44235.firebasestorage.app',
    iosBundleId: 'com.neurocare.connect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2cNTdovGJEfOADOlBrz3kNyHg0n1a0Vw',
    appId: '1:453591806698:web:99a7e7487b0c28a543dd93',
    messagingSenderId: '453591806698',
    projectId: 'neurocare-connect-44235',
    authDomain: 'neurocare-connect-44235.firebaseapp.com',
    storageBucket: 'neurocare-connect-44235.firebasestorage.app',
    measurementId: 'G-BWK65P7FSW',
  );

}