// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI40j9uTXzmOf9bqPuoRvB1DZaFXPXHc0',
    appId: '1:214738954591:web:4ad410fb0ba062485f6eea',
    messagingSenderId: '214738954591',
    projectId: 'kivicareneurocare',
    authDomain: 'kivicareneurocare.firebaseapp.com',
    storageBucket: 'kivicareneurocare.firebasestorage.app',
    measurementId: 'G-JC681ZPPMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBwddeG80wz19VNhbQ7rl6bDq49csTgNo',
    appId: '1:214738954591:android:af631842b1fa21515f6eea',
    messagingSenderId: '214738954591',
    projectId: 'kivicareneurocare',
    storageBucket: 'kivicareneurocare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe2FTjoIK44oYsWjwd51nOtkLAt5MIsrA',
    appId: '1:214738954591:ios:b573181593e10e3d5f6eea',
    messagingSenderId: '214738954591',
    projectId: 'kivicareneurocare',
    storageBucket: 'kivicareneurocare.firebasestorage.app',
    iosBundleId: 'com.neurocare.neurocaretelemed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI40j9uTXzmOf9bqPuoRvB1DZaFXPXHc0',
    appId: '1:214738954591:web:fa1ce403e06ef5635f6eea',
    messagingSenderId: '214738954591',
    projectId: 'kivicareneurocare',
    authDomain: 'kivicareneurocare.firebaseapp.com',
    storageBucket: 'kivicareneurocare.firebasestorage.app',
    measurementId: 'G-4BMH42JX8Z',
  );

}