name: Flutter CI (Android Debug+Release, Web, Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java (Android Gradle Plugin req.)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      # IMPORTANT : crée la plateforme Android ici, avec un nom de projet valide et un org unique
      - name: Create Android platform (force valid name + org)
        run: flutter create --platforms=android --project-name neurocare_connect --org tech.neurocareconnect .

      - name: Flutter pub get
        run: flutter pub get

      # APK DEBUG (installable sans clé de prod)
      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # APK RELEASE (non signé par défaut ; utile pour tests/CI)
      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact (release)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Enable web
        run: flutter config --enable-web

      - name: Create Web platform (force valid name)
        run: flutter create --platforms=web --project-name neurocare_connect .

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Web (release)
        run: flutter build web --release

      - name: Upload Web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Create Windows platform (force valid name)
        run: flutter create --platforms=windows --project-name neurocare_connect .

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Windows (release)
        run: flutter build windows --release

      # Archive prête à l'emploi (contient l'EXE + dll + assets)
      - name: Zip Windows release
        run: |
          powershell -Command "Compress-Archive -Path 'build/windows/x64/runner/Release/*' -DestinationPath 'build/windows/x64/runner/windows-release.zip' -Force"

      - name: Upload Windows ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-zip
          path: build/windows/x64/runner/windows-release.zip
